### ISSUE TITLE
Unable to set mouse buttons as keybinds

### ISSUE THREAD

**Issue by vanirfreyr** [RaidcoreGG/Nexus#53]
It seems mouse buttons aren't recognized for keybind management. This is very crucial to the way I play and would love to see it implemented in future! --Or if there is a setting I'm missing which would allow this, do please let me know!
Thank you!

**Comment by DeltaGW2** [comment]
This is currently unsupported, but will follow in one of the next updates!

The internal Keybinds API has been undergoing a lot of changes and this was one of the main goals, among others such as potential Gamepad support.

**Comment by DeltaGW2** [comment]
@vanirfreyr Latest release added mouse support!
