### ISSUE TITLE
Request: Can you please hide the Nexus icon when GW2 UI is hidden?

### ISSUE THREAD

**Issue by kazerniel** [RaidcoreGG/Nexus#56]
The "during gameplay" visibility option is great for vistas and loading screens, but it would be nice if the icon also got hidden when GW2's own "hide UI" hotkey is toggled.

**Comment by DeltaGW2** [comment]
The Nexus "Toggle Hide UI" Keybind already passes the inputs through to the game.
Meaning if you set your in-game bind to "CTRL+SHIFT+H" and your Nexus one too, it will hide both at the same time.

(Ignore the German naming lol)
![image](https://github.com/user-attachments/assets/740fbf8d-95ca-43be-9919-be795984bb40)

Automatically detecting whether the game's UI is hidden is not possible without memory reading, which Nexus doesn't do.

**Comment by kazerniel** [comment]
Thank you! Now I know what those keybinds do :)
